<a href="https://colab.research.google.com/github/Tokhirjonov15/AI_Foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

pd.__version__

'2.2.2'

Series

In [ ]:
l = [1, 2, 3, 4]
sr = pd.Series(l, dtype=np.int32, index=["a", 'b', 'c', 'd'])
sr

a    1
b    2
c    3
d    4
dtype: int32

In [ ]:
sr**2
sr.astype(np.int16)

a    1
b    2
c    3
d    4
dtype: int16

DataFrame

In [ ]:
df = pd.DataFrame(l, columns=['a'])
df

   a
0  1
1  2
2  3
3  4

In [ ]:
df['a']

0    1
1    2
2    3
3    4
Name: a, dtype: int64

In [ ]:
x = np.arange(0,40)
print("Arange Arrays:", x)

Arange Arrays: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]

In [ ]:
y = np.cos(x)
print("Cosinus of Arrays above:", y)

Cosinus of Arrays above: [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462  0.40808206 -0.54772926 -0.99996083 -0.53283302
  0.42417901  0.99120281  0.64691932 -0.29213881 -0.96260587 -0.74805753
  0.15425145  0.91474236  0.83422336 -0.01327675 -0.84857027 -0.90369221
 -0.12796369  0.76541405  0.95507364  0.26664293]

In [ ]:
df = pd.DataFrame({'x':x, 'y=cos(x)':y})
df

     x  y=cos(x)
0    0  1.000000
1    1  0.540302
2    2 -0.416147
3    3 -0.989992
4    4 -0.653644
5    5  0.283662
6    6  0.960170
7    7  0.753902
8    8 -0.145500
9    9 -0.911130
10  10 -0.839072
11  11  0.004426
12  12  0.843854
13  13  0.907447
14  14  0.136737
15  15 -0.759688
16  16 -0.957659
17  17 -0.275163
18  18  0.660317
19  19  0.988705
20  20  0.408082
21  21 -0.547729
22  22 -0.999961
23  23 -0.532833
24  24  0.424179
25  25  0.991203
26  26  0.646919
27  27 -0.292139
28  28 -0.962606
29  29 -0.748058
30  30  0.154251
31  31  0.914742
32  32  0.834223
33  33 -0.013277
34  34 -0.848570
35  35 -0.903692
36  36 -0.127964
37  37  0.765414
38  38  0.955074
39  39  0.266643

In [ ]:
df.head(9)  # head() qiymatlarni boshidan chiqaradi

   x  y=cos(x)
0  0  1.000000
1  1  0.540302
2  2 -0.416147
3  3 -0.989992
4  4 -0.653644
5  5  0.283662
6  6  0.960170
7  7  0.753902
8  8 -0.145500

In [ ]:
df.tail(5)  # tail() qiymatlarni oxiridan chiqaradi

     x  y=cos(x)
35  35 -0.903692
36  36 -0.127964
37  37  0.765414
38  38  0.955074
39  39  0.266643

In [ ]:
df.sample(5)  # sample() random holatda DataFramelarni tanlab beradi

     x  y=cos(x)
29  29 -0.748058
17  17 -0.275163
2    2 -0.416147
39  39  0.266643
22  22 -0.999961

In [7]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Kia", "Chevrolet"],
  'counts': [3, 7, 2, 8, 1, 4]
}

df = pd.DataFrame(mydataset)

print(df)

        cars  counts
0        BMW       3
1      Volvo       7
2       Ford       2
3      Tesla       8
4        Kia       1
5  Chevrolet       4

In [8]:
df.shape

(6, 2)

In [9]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [10]:
df.dtypes

cars      object
counts     int64
dtype: object

In [14]:
df.describe()  # numerical columns only

         counts
count  6.000000
mean   4.166667
std    2.786874
min    1.000000
25%    2.250000
50%    3.500000
75%    6.250000
max    8.000000

In [18]:
df.iloc[1:4]

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       8

In [19]:
df.loc[:, "cars"]

0          BMW
1        Volvo
2         Ford
3        Tesla
4          Kia
5    Chevrolet
Name: cars, dtype: object

In [21]:
df[df["counts"] > 3]  # #dan kattasini olib beradi

        cars  counts
1      Volvo       7
3      Tesla       8
5  Chevrolet       4

In [23]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(4.166666666666667)

In [24]:
df.sum()

cars      BMWVolvoFordTeslaKiaChevrolet
counts                               25
dtype: object

In [25]:
df.median(numeric_only=True)

counts    3.5
dtype: float64

In [26]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Kia", None],
    "counts": [3, 7, None, 8, None, 4]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

    cars  counts
0    BMW     3.0
1  Volvo     7.0
2   None     NaN
3  Tesla     8.0
4    Kia     NaN
5   None     4.0

In [28]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [30]:
df_missing.dropna(how="all")   # (axis=1) agar columnda Falsy value bo'lsa columnni butunlat o'chiradi. # (subset=['counts']) bu faqat counts columnni tekshirib beradi

    cars  counts
0    BMW     3.0
1  Volvo     7.0
3  Tesla     8.0
4    Kia     NaN
5   None     4.0

In [33]:
df_missing.fillna({"cars": "unknowm", "counts": 0}) # Falsy valuelarga qiymat qo'shish

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknowm     0.0
3    Tesla     8.0
4      Kia     0.0
5  unknowm     4.0

In [36]:
# df = pd.read_csv("Titanic-Dataset.csv")

# df.head()

df = pd.read_excel("output.xlsx")
df.head()
# df = pd.read_json("file_name.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [35]:
df.to_excel("output.xlsx")